ui/relay/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns(
    '',
    (r'^relay/admin/', include('django.contrib.admin.urls')),
    (r'^relay/warnings/', include('relay.warnings.urls')),
    )

ui/relay/warnings/urls.py
from django.conf.urls.defaults import *
from relay.warnings.models import *

codebases = {
    'queryset': Code_base.objects.all(),
    }

runs = {
    'queryset': Run.objects.all(),
    }

raceclusters = {
    'queryset': Race_cluster.objects.all(),
    }

races = {
    'queryset': Race.objects.all(),
    }

from relay.warnings import views
from django.contrib import databrowse



urlpatterns = patterns(
    '',
    (r'^$', views.code_list, dict(codebases, paginate_by=30)),
    (r'^dbrowse/(.*)', databrowse.site.root),
    (r'^program/(?P<object_id>\d+)/$', views.code_detail,
     codebases),
    (r'^run/(?P<object_id>\d+)/$', views.run_detail, runs),
    (r'^run/(?P<run_id>\d+)/race_warn/$', views.race_warn_list),
    (r'^race_warn/(?P<object_id>\d+)/$', views.warn_detail,
     raceclusters),
    (r'^run/(?P<run_id>\d+)/search/$', views.search),
    
)

databrowse.site.register(Run)
databrowse.site.register(Race_cluster)
databrowse.site.register(Label)

ui/relay/warnings/models.py
from django.db import models
from django.db.models import permalink
import re
import sys

def warn(msg):
    sys.stderr.write(msg)

class Code_base(models.Model):
    program_name = models.CharField(max_length=50, core=True)
    version = models.CharField(max_length=40, core=True)
    compile_options = models.CharField(max_length=100)
    def __str__(self):
        return "%s v.%s" % (self.program_name, self.version)
    def get_absolute_url(self):
        return ('relay.warnings.views.code_detail', [str(self.id)])
    get_absolute_url = permalink(get_absolute_url)
    class Admin:
        # Admin options go here
        pass

class Note(models.Model):
    explaination = models.TextField(core=True)
    last_updated = models.DateTimeField(core=True, auto_now=True)
    def __str__(self):
        return "%s %s" % (self.explaination, self.last_updated)
    class Admin:
        # Admin options go here
        pass

class Label(models.Model):
    label = models.CharField(max_length=50, core=True)
    example = models.TextField(core=True)
    def __str__(self):
        return self.label
    class Admin:
        # Admin options go here
        pass

def first_labels(n, ls):
    reduce(lambda x, y: x + ", " + y, ls.all()[0:n], "")

class Function(models.Model):
    cil_id = models.IntegerField(core=True, db_index=True)
    name = models.CharField(max_length=50, core=True)
    labels = models.ManyToManyField(Label, filter_interface=models.VERTICAL)
    program = models.ForeignKey(Code_base, limit_choices_to={})
    def __str__(self):
        return "%s (%d)" % (self.name, self.cil_id)
    def first_labels(self):
        return first_labels(2, self.labels)
    class Admin:
        list_display = ('cil_id', 'name', 'program', 'first_labels')

class Program_point(models.Model):
    file_name = models.CharField(max_length=100, core=True)
    line_num = models.IntegerField(core=True, db_index=True)
    parent_function = models.ForeignKey(Function,
                                        null=True, limit_choices_to={})
    def __str__(self):
        return "%d in %s" % (self.line_num, self.file_name)
    class Admin:
        # Admin options go here
        pass
    
class Lval(models.Model):
    var_id = models.IntegerField(null=True, db_index=True)
    printed = models.CharField(max_length=100, core=True)
    rep_size = models.IntegerField(null=True)
    declared_at = models.ForeignKey(Program_point, null=True)
    is_global = models.BooleanField()
    def __str__(self):
        s = self.printed
        if (self.var_id):
            s += " (%d)" % self.var_id
        if (self.rep_size):
            s += " |%d|" % self.rep_size
        return s
    class Admin:
        # Admin options go here
        pass

class Call_path(models.Model):
    root_function = models.ForeignKey(Function, limit_choices_to={})
    spawn_site = models.ForeignKey(Program_point,
                                   related_name="spawns", limit_choices_to={})
    empty_ls = models.ForeignKey(Program_point,
                                 related_name="empty_ls", null=True,
                                 limit_choices_to={})
    # not including the edges right now...
    def __str__(self):
        return self.root_function.__str__() + " -> ..."
    def program(self):
        return str(self.root_function.program)
    class Admin:
        list_display = ('program', 'root_function', 'spawn_site')


class Call_edge(models.Model):
    path = models.ForeignKey(Call_path, limit_choices_to={})
    caller = models.ForeignKey(Function, related_name="is_caller",
                               limit_choices_to={})
    callee = models.ForeignKey(Function, related_name="is_callee",
                               limit_choices_to={})
    def __str__(self):
        return str(self.caller) + " -> " + str(self.callee)
    class Admin:
        # Admin options go here
        pass

class Access(models.Model):
    lval = models.ForeignKey(Lval, related_name="reads_writes")
    accessed_through = models.ForeignKey(Call_path)
    occurs_at = models.ForeignKey(Program_point)
    locks = models.ManyToManyField(Lval, filter_interface=models.VERTICAL)
    def __str__(self):
        return str(self.lval) + " @ " + str(self.occurs_at)
    def has_lock(self):
        return len(self.locks.all()[:1]) != 0
    has_lock.boolean = True
    class Admin:
        list_display = ('lval', 'occurs_at', 'has_lock')
        search_fields = ['occurs_at']

class Run(models.Model):
    time_of_run = models.DateTimeField(editable=True, auto_now_add=True)
    code = models.ForeignKey(Code_base, limit_choices_to={})
    changes_to_analysis = models.TextField(core=True)
    analysis_settings = models.TextField(core=True)
    def __str__(self):
        return str(self.code) + " " + str(self.time_of_run)
    def get_absolute_url(self):
        return ('relay.warnings.views.run_detail', [str(self.id)])
    get_absolute_url = permalink(get_absolute_url)
    class Admin:
        list_display = ('id', 'code', 'time_of_run')
        list_filter = ('code', 'time_of_run')

class Race(models.Model):
    access1 = models.ForeignKey(Access, core=True, related_name="racy1")
    access2 = models.ForeignKey(Access, core=True, related_name="racy2")
    note = models.ForeignKey(Note, core=True, null=True)
    labels = models.ManyToManyField(Label, filter_interface=models.VERTICAL)
    def __str__(self):
        return str(self.access1) + " [X] " + str(self.access2)
    def first_labels(self):
        return first_labels(2, self.labels)
    def add_label(self, label):
        self.labels.add(label)
    def remove_label(self, label):
        self.labels.remove(label)
    class Admin:
        list_display = ('access1', 'access2', 'first_labels')

class Race_cluster(models.Model):
    races = models.ManyToManyField(Race, filter_interface=models.VERTICAL)
    run = models.ForeignKey(Run)
    cluster_id = models.IntegerField(null=True, core=True)
    def program(self):
        return str(self.run.code)
    def first_race(self):
        return str(self.races.all()[0])
    def get_absolute_url(self):
        return ('relay.warnings.views.warn_detail', [str(self.id)])
    get_absolute_url = permalink(get_absolute_url)
    def add_label(self, label):
        for r in self.races.all():
            r.add_label(label)
    def remove_label(self, label):
        for r in self.races.all():
            r.remove_label(label)
    class Admin:
        list_display = ('program', 'run', 'first_race')
        list_filter = ('run',)


#---- Constructors that either get old matches, or creates new objs -----

def getCodeBase(name, ver, opt):
    return Code_base.objects.get_or_create (program_name=name, version=ver, compile_options = opt)

def getFunc(c_id, n, prog):
    c_id = int(c_id)
    return Function.objects.get_or_create (cil_id=c_id, name=n, program=prog)

def findFunc(c_id, prog):
    try:
        c_id = int(c_id)
        f = Function.objects.get(cil_id=c_id, program=prog)
        return f
    except:
        warn('Function not found %d\n' % c_id)
        return None

def getPP(f, line, parent):
    args = {'line_num' : int(line), 'file_name' : f}
    # NULL != NULL in SQL sucks...
    if (parent == None):
        args['parent_function__isnull'] = True
    else:
        args['parent_function'] = parent
    obj, created = Program_point.objects.get_or_create(**args)
    return obj

def getLval(vid, p_rep, size, decl, glob):
    # NULL != NULL in SQL sucks...
    args = {'printed' : p_rep , 'is_global' : glob }
    if (vid == None):
        args['var_id__isnull'] = True
    else:
        args['var_id'] = int(vid)
    if(size == None):
        args['rep_size__isnull'] = True
    else:
        args['rep_size'] = int(size)
    if(decl == None):
        args['declared_at__isnull'] = True
    else:
        args['declared_at'] = decl
    obj, created = Lval.objects.get_or_create(**args)
    return obj


def getCallpath(root, spawn, empty_at, edges):
    found = None
    args = { 'root_function' : root, 'spawn_site' : spawn }
    filt_args = {}
    create_args = {}
    filt_args.update(args)
    if (empty_at == None):
        filt_args['empty_ls__isnull'] = True
    else:
        filt_args['empty_ls'] = empty_at
    matches = Call_path.objects.select_related().filter(**filt_args)
    edges.sort()
    # see which of the old call paths have the same set of edges
    for o in matches:
        db_edges = Call_edge.objects.filter(path=o).order_by(
            'caller', 'callee')
        e = [(e.caller, e.callee) for e in db_edges]
        if (e == edges) :
            found = o
            break
    # if it didn't find any call paths w/ the same set of edges
    if (not found) :
        create_args.update(args)
        create_args['empty_ls'] = empty_at
        found = Call_path.objects.create(**create_args)
        for (f1, f2) in edges :
            Call_edge.objects.create(path=found, caller=f1, callee=f2)
    return found

#-------- Access factories

def matchLocksAccesses (accessMatches, locks):
    found = None
    for old in accessMatches:
        db_l = list(old.locks.all())
        if (db_l == locks) :
            found = old
            break
    if (not found) :
        found = Access.objects.create(lval=lv,accessed_through=cp,occurs_at=pp)
        found.locks = locks
        found.save()
    return found


def getAccess(lv, cp, pp, locks):
    # make sure lists are in sorted order before comparing
    locks.sort()
    matches = Access.objects.select_related().filter(lval=lv, accessed_through=cp, occurs_at=pp)
    # see which of the old accesses have the same set of locks
    found = matchLocksAccesses (matches, locks)
    return found


def createAccess(lv, cp, pp, locks):
    acc = Access.objects.create(lval=lv, accessed_through=cp, occurs_at=pp)
    acc.locks = locks
    acc.save()
    return acc


def getAccesses(lv, cp, pps, locks):
    res = []
    locks.sort()

ui/relay/warnings/views.py
# Create your views here.

from relay.warnings.models import *
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.views.generic.list_detail import object_list, object_detail

def code_list(*args, **kwargs):
    return object_list(*args, **kwargs)

def code_detail(*args, **kwargs):
    return object_detail(*args, **kwargs)

def run_detail(*args, **kwargs):
    return object_detail(*args, **kwargs)

def race_warn_list(request, run_id):
    args =[request]
    kwargs = {}
    try:
        r = Run.objects.get(id=run_id)
        kwargs['queryset'] = Race_cluster.objects.filter(run = r)
        kwargs['paginate_by'] = 50
        return object_list(*args, **kwargs)
    except KeyError, Run.DoesNotExist:
        raise Http404


def warn_detail(request, object_id):
    warn = Race_clusters.objects.get(id=object_id)
    labels = warn.races.first_race().labels().all
    return object_detail(request, queryset=warn, 
                         extra_context={'labels' : labels,
                                        'someInt' : 10})


def search(request, run_id):
    from relay.warnings.search import SearchForm
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            # Do form processing here...
            raise Http404
    form = SearchForm()
    print run_id
    r = Run.objects.get(id = run_id)
    rcs = Race_cluster.objects.filter(run=r)
    return render_to_response('warnings/search.html', 
                              {'form': form , 'run' : r , 'races' : rcs ,
                               'run_id' : run_id})

ui/templates/warnings/code_base_detail.html
{% extends "base.html" %}

{% block title %}{{ object}}{% endblock %}

{% block content %}
    <h1>{{ object.program_name }}</h1>
    <ul>
      <li>version: {{ object.version }}</li>
      <li>compiler options: {{ object.compile_options }}</li>
    </ul>
    
    <h2>Runs</h2>
    <ul>
      {% for run in object.run_set.all %}
      <li><a href="{{ run.get_absolute_url }}">{{ run.time_of_run }}</a></li>
      {% endfor %}
    </ul>

{% endblock %}

ui/templates/warnings/code_base_list.html
{% extends "base.html" %}

{% block title %} Programs checked {% endblock %}

{% block content %}

   {% if object_list %}
    <h1> Programs checked </h1>
    <ul>
      {% for codebase in object_list %}
      <li><a href="{{ codebase.get_absolute_url }}">
          {{ codebase }} 
          </a></li>
    {% endfor %}
    </ul>
   {% else %}
    <p>No code bases are available.</p>
   {% endif %}

{% endblock %}

ui/templates/warnings/race_cluster_detail.html
{% extends "base.html" %}

{% block title %} Warning #{{ object.id }} {% endblock %}

{% block content %}
<div class="module">
    <h1>Race Warning id: {{ object.id }} </h1>
    
    <h2>From program</h2>
    <p>{{object.program}}</p>
    <h2>Races (grouped by access 1's line number) </h2>
    {% regroup object.races.all|dictsort:"access1.occurs_at.line_num" by access1 as acc1_groups %}
    {% regroup object.races.all|dictsort:"access2.occurs_at.line_num" by access2 as acc2_groups %}
{# assuming races were just a cross product of a list of acc1 and acc2 #}
    <table width="100%">
      <thead>
        <tr>
          <th>Acc#</th><th>Lval</th><th>Occurs at</th><th>Locks held</th>
          <th>Access path</th><th>Loses lock at</th>
        </tr>
      </thead>
      <tbody>

      {% for group in acc1_groups %}
      <tr class="{% cycle row1,row2 %}">
        <th>1</th>
        <td>{% ifchanged group.grouper.lval %} 
            {{ group.grouper.lval.printed|escape }} {% endifchanged %}</td>
        <td>{{ group.grouper.occurs_at }}</td>
        <td>{% ifchanged group.grouper.locks %} 
              [{% for l in group.grouper.locks.all %} {{ l|escape }} 
              {% endfor %}] {% endifchanged %}
        </td>
        <td>{% ifchanged group.grouper.accessed_through %} 
            {{ group.grouper.accessed_through }} {% endifchanged %}</td>
        <td>{% ifchanged group.grouper.accessed_through.empty_ls %}
              {{ group.grouper.accessed_through.empty_ls }} 
              {% endifchanged %}</td>
      {% endfor %}

      {% for group in acc2_groups %}
      <tr class="{% cycle row1,row2 %}">
        <th>2</th>
        <td>{% ifchanged group.grouper.lval %} 
            {{ group.grouper.lval.printed|escape }} {% endifchanged %}</td>
        <td>{{ group.grouper.occurs_at }}</td>
        <td>{% ifchanged group.grouper.locks %} 
              [{% for l in group.grouper.locks.all %} {{ l|escape }} 
              {% endfor %}] {% endifchanged %}
        </td>
        <td>{% ifchanged group.grouper.accessed_through %} 
            {{ group.grouper.accessed_through }} {% endifchanged %}</td>
        <td>{% ifchanged group.grouper.accessed_through.empty_ls %}
              {{ group.grouper.accessed_through.empty_ls }} 
              {% endifchanged %}</td>
      {% endfor %}
      </tbody>
    </table>
</div>
    <p>Labels:
      {% if labels %}
         labels is here!
      {% endif %}
      {{ labels }}
      {% for label in labels %}
      {{ label }}
      {% endfor %}
    </p>
{% endblock %}

ui/templates/warnings/race_cluster_list.html
{% extends "base.html" %}

{% block title %} List of races {% endblock %}

{% block content %}

   {% if object_list %}
    <h1> Races for run XXX </h1>
    <ul>
      {% for rc in object_list %}
      <li><a href="{{ rc.get_absolute_url }}">
          Race #{{ rc.id }} 
          </a></li>
    {% endfor %}
    </ul>
   {% else %}
    <p>No code bases are available.</p>
   {% endif %}

{% endblock %}

ui/templates/warnings/run_detail.html
{% extends "base.html" %}

{% block title %} Run on {{object}}  at  {% endblock %}

{% block content %}
<div class="module">
<table width="100%">
   <caption><big>Run on {{ object }} </big></caption>
    
   <tr><td><h4>Changes to analysis</h4>
      <p> {{ object.changes_to_analysis }}</p>
       </td></tr>
   <tr><td><h4>Analysis settings</h4>
    <p> {{ object.analysis_settings }}</p>
       </td></tr>
</table>
</div>
{% endblock %}

{% block sidebar %}
{% include "warnings/util_side.html" %}
{% endblock %}

ui/templates/warnings/search.html
{% extends "base.html" %}

{% block title %} Search for run on {{ run }}   {% endblock %}

{% block content %}
    <h1>Search for run {{ run }}</h1>

    <form method="post">
      <table> {{form.as_table}} </table>
      <input type="submit">
    </form>

{% endblock %}

ui/templates/warnings/util_side.html
<div class="module">
  <table width="100%"> 
  <caption>Utilities</caption>
  <tbody>
     <tr><td><a href="search/">Search</a></td></tr>
     <tr><td>Labels:</td></tr>
  </tbody>
  </table>
</div>